- hosts: all
  sudo: yes
  
  tasks:
  - name: Add repo apt.postgresql.org
    apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main 9.6' state=present
  
  - name: Add key repo apt.postgresql.org
    apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

  - name: Update repository
    apt: update_cache=yes

  - name: Install sofware
    apt: name={{ item }} state=present
    with_items:
    - postgresql-9.6