- hosts: all
  sudo: yes
  vars:
    dumpDataBaseFile: '/tmp/hawks.gz'
    dumpRoleFile: '/tmp/role.gz'
    baseName: 'hawks'
    roleName: 'role'

  tasks:
  - name: Copy dump database
    copy: src={{dumpDataBaseFile}} dest={{dumpDataBaseFile}}

  - name: Copy dump role
    copy: src={{dumpRoleFile}} dest={{dumpRoleFile}}

  - name: Gunzip dump database
    command: gunzip {{dumpDataBaseFile}}

  - name: Gunzip dump role
    command: gunzip {{dumpRoleFile}}

  - name: Create db
    command: createdb -O hawks_user --encoding='UTF8' --locale=en_US.UTF-8 --template=template0 hawks
    become: yes
    become_user: postgres
    become_method: sudo

  - name: Restore dump role
    command: psql {{baseName}} -f /tmp/{{roleName}}
    become: yes
    become_user: postgres
    become_method: sudo

  - name: Restore dump database
    command: psql {{baseName}} -f /tmp/{{baseName}}
    become: yes
    become_user: postgres
    become_method: sudo

  - name: Remove migration file database
    command: rm /tmp/{{baseName}}

  - name: Remove role file database
    command: rm /tmp/{{roleName}}